name: operation_won
description: an app i suppose
publish_to: none
version: 0.0.1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  flutter_html: ^3.0.0-beta.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.7
  lucide_icons_flutter: ^3.0.7
  nowa_runtime: ^0.0.44
  permission_handler: ^12.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  web_socket_channel: ^3.0.3
  wakelock_plus: ^1.3.2
  opus_flutter: ^3.0.1
  opus_dart: ^3.0.1
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
