name: operation_won
description: an app i suppose
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  flutter_html: ^3.0.0-beta.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.7
  lucide_icons_flutter: ^3.0.7
  nowa_runtime: ^0.0.44
  permission_handler: ^11.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  web_socket_channel: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
