name: operation_won
description: Operation Won.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  # newrelic_mobile: 1.0.5
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dart_ping: ^9.0.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.8
  agora_rtc_engine: ^6.2.6
  permission_handler: ^11.1.0
  http: ^1.1.2
  audio_service: ^0.18.12
  flutter_onboarding_slider: ^1.0.11
  sentry_flutter: ^7.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.4
#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/e.png"
#   min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  color: "#3b0412"
  image: assets/e.png
  android: true
  ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/e.png
    - assets/entire_e.png
    - assets/header.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: ABCSans
      fonts:
        - asset: fonts/ABCSans/abcsans-black.otf
          # style: black
        - asset: fonts/ABCSans/abcsans-bold.otf
          # style: bold
        - asset: fonts/ABCSans/abcsans-light.otf
          # style: light
        - asset: fonts/ABCSans/abcsans-regular.otf
        - asset: fonts/ABCSans/abcsans-regularitalic.otf
          style: italic
    - family: Azeret_Mono
      fonts:
        - asset: fonts/Azeret_Mono/AzeretMono-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/Azeret_Mono/AzeretMono-VariableFont_wght.ttf
    - family: Gilroy_Black
      fonts:
        - asset: fonts/Gilroy/Gilroy-Black.ttf
          # style: black
        - asset: fonts/Gilroy/Gilroy-BlackItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-Bold.ttf
          # style: bold
        - asset: fonts/Gilroy/Gilroy-BoldItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-ExtraBold.ttf
          # style: extra_bold
        - asset: fonts/Gilroy/Gilroy-ExtraBoldItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-Heavy.ttf
          # style: heavy
        - asset: fonts/Gilroy/Gilroy-HeavyItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-Light.ttf
          # style: light
        - asset: fonts/Gilroy/Gilroy-LightItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-Medium.ttf
          # style: medium
        - asset: fonts/Gilroy/Gilroy-MediumItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-Regular.ttf
        - asset: fonts/Gilroy/Gilroy-RegularItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-SemiBold.ttf
          # style: semi_bold
        - asset: fonts/Gilroy/Gilroy-SemiBoldItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-Thin.ttf
          # style: thin
        - asset: fonts/Gilroy/Gilroy-ThinItalic.ttf
          style: italic
        - asset: fonts/Gilroy/Gilroy-UltraLight.ttf
          # style: ultra_light
        - asset: fonts/Gilroy/Gilroy-UltraLightItalic.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Variable.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
          # style: bold
        - asset: fonts/Roboto_Condensed/RobotoCondensed-BoldItalic.ttf
          style: italic
        - asset: fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
          # style: light
        - asset: fonts/Roboto_Condensed/RobotoCondensed-LightItalic.ttf
          style: italic
        - asset: fonts/Roboto_Condensed/RobotoCondensed-Italic.ttf
          style: italic
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi/Satoshi_Complete/Fonts/OTF/Satoshi-Regular.otf
        - asset: fonts/Satoshi/Satoshi_Complete/Fonts/OTF/Satoshi-Italic.otf
          style: italic
    - family: SatoshiBold
      fonts:
        - asset: fonts/Satoshi/Satoshi_Complete/Fonts/OTF/Satoshi-Bold.otf